"""Alembic's entry point — how it finds the database and the models.

Two things are wired up here that the generated template doesn't do:

1. The URL comes from the app's own config (so `.env` / Secret Manager is the
   single source of truth), not from a URL written into alembic.ini.
2. `include_object` hides LangChain's pgvector tables. They are created by
   LangChain itself, so they are absent from Base.metadata — without this
   filter, autogenerate would see them as tables nobody wants and write a
   `drop_table` for each, deleting every embedding.
"""
from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool

from alembic import context
from app.core import config as app_config
from app.models import Base

config = context.config
config.set_main_option("sqlalchemy.url", app_config.DATABASE_URL)

# Only when run from the CLI: the app sets configure_logger=False so a startup
# migration doesn't reconfigure the server's logging out from under it.
if config.config_file_name is not None and config.attributes.get(
    "configure_logger", True
):
    fileConfig(config.config_file_name)

target_metadata = Base.metadata

# Tables Alembic must never touch: LangChain owns these.
NOT_OURS = ("langchain_pg_collection", "langchain_pg_embedding")


def include_object(obj, name, type_, reflected, compare_to) -> bool:
    """Keep LangChain's own tables out of every autogenerated migration."""
    if type_ == "table" and name in NOT_OURS:
        return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout instead of running it, for review or manual apply."""
    context.configure(
        url=config.get_main_option("sqlalchemy.url"),
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_object=include_object,
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect and run the migrations for real."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            # Notice a column changing type or nullability, not just added
            # and dropped tables.
            compare_type=True,
            compare_server_default=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
