"""drop the unused session_id column

Revision ID: 6d7980810396
Revises: 1ee86fa50fef
Create Date: 2026-07-21 13:00:06.235277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d7980810396'
down_revision: Union[str, Sequence[str], None] = '1ee86fa50fef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
